driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5432/db?ssl=false
user=user
password=mystrongpassword
changeLogFile:liquibase/changelog-master.yaml
secret=secretjwtworkdemosenlacoursesforauthenticationandregisterationouruser
expired=3600000